export const FETCH_EVENTS_REQUEST = "FETCH_EVENTS_REQUEST";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE";
export const SELECT_DATE = "SELECT_DATE";
export const ADJUST_MAP = "ADJUST_MAP";
export const ADD_EVENT = "ADD_EVENT";
